Repository sb3-otboo-team2/sb3-otboo-team2, pull requests merged in 2025-09, with the labels that each got.

#9 [Clothes] 의상 삭제 기능 구현
  src/main/java/org/ikuzo/otboo/domain/clothes/controller/ClothesController.java
  src/main/java/org/ikuzo/otboo/domain/clothes/controller/api/ClothesApi.java
  src/main/java/org/ikuzo/otboo/domain/clothes/service/ClothesService.java
  src/main/java/org/ikuzo/otboo/domain/clothes/service/impl/ClothesServiceImpl.java
  src/main/java/org/ikuzo/otboo/global/util/ImageSwapHelper.java
Labels: Feat

#12 [User] 회원가입
  build.gradle
  src/main/java/org/ikuzo/otboo/domain/user/controller/UserController.java
  src/main/java/org/ikuzo/otboo/domain/user/dto/UserCreateRequest.java
  src/main/java/org/ikuzo/otboo/domain/user/dto/UserDto.java
  src/main/java/org/ikuzo/otboo/domain/user/entity/User.java
  src/main/java/org/ikuzo/otboo/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/org/ikuzo/otboo/domain/user/exception/UserException.java
  src/main/java/org/ikuzo/otboo/domain/user/mapper/UserMapper.java
  src/main/java/org/ikuzo/otboo/domain/user/repository/UserRepository.java
  src/main/java/org/ikuzo/otboo/domain/user/service/UserService.java
  src/main/java/org/ikuzo/otboo/domain/user/service/UserServiceImpl.java
  src/main/java/org/ikuzo/otboo/global/config/SecurityConfig.java
  src/main/java/org/ikuzo/otboo/global/exception/ErrorCode.java
  src/main/java/org/ikuzo/otboo/global/exception/GlobalExceptionHandler.java
Labels: Feat

#14 [Clothes] 의상 목록 조회 기능 구현
  src/main/java/org/ikuzo/otboo/domain/clothes/controller/ClothesController.java
  src/main/java/org/ikuzo/otboo/domain/clothes/controller/api/ClothesApi.java
  src/main/java/org/ikuzo/otboo/domain/clothes/exception/ClothesDtoConvertingFailedException.java
  src/main/java/org/ikuzo/otboo/domain/clothes/repository/ClothesRepository.java
  src/main/java/org/ikuzo/otboo/domain/clothes/repository/ClothesRepositoryCustom.java
  src/main/java/org/ikuzo/otboo/domain/clothes/repository/ClothesRepositoryImpl.java
  src/main/java/org/ikuzo/otboo/domain/clothes/service/ClothesService.java
  src/main/java/org/ikuzo/otboo/domain/clothes/service/impl/ClothesServiceImpl.java
  src/main/java/org/ikuzo/otboo/global/exception/ErrorCode.java
Labels: Feat

#20 [Notification] SSE 알림 생성
  src/main/java/org/ikuzo/otboo/domain/follow/service/FollowServiceImpl.java
  src/main/java/org/ikuzo/otboo/domain/notification/dto/NotificationDto.java
  src/main/java/org/ikuzo/otboo/domain/notification/entity/Notification.java
  src/main/java/org/ikuzo/otboo/domain/notification/mapper/NotificationMapper.java
  src/main/java/org/ikuzo/otboo/domain/notification/repository/NotificationRepository.java
  src/main/java/org/ikuzo/otboo/domain/notification/service/NotificationService.java
  src/main/java/org/ikuzo/otboo/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/ikuzo/otboo/global/event/listener/NotificationRequiredEventListener.java
  src/main/java/org/ikuzo/otboo/global/event/listener/SseRequiredEventListener.java
  src/main/java/org/ikuzo/otboo/global/event/listener/WebsocketRequiredEventListener.java
  src/main/java/org/ikuzo/otboo/global/event/message/CreatedEvent.java
  src/main/java/org/ikuzo/otboo/global/event/message/FollowCreatedEvent.java
  src/main/java/org/ikuzo/otboo/global/event/message/MessageCreatedEvent.java
  src/main/java/org/ikuzo/otboo/global/event/message/NotificationCreatedEvent.java
  src/main/java/org/ikuzo/otboo/global/sse/controller/SseController.java
  src/main/java/org/ikuzo/otboo/global/sse/entity/SseMessage.java
  src/main/java/org/ikuzo/otboo/global/sse/repository/SseEmitterRepository.java
  src/main/java/org/ikuzo/otboo/global/sse/repository/SseMessageRepository.java
  src/main/java/org/ikuzo/otboo/global/sse/service/SseService.java
  src/main/resources/application.yaml
  src/main/resources/schema.sql
Labels: Feat

#18 [Weather] 카카오/기상청 API 불러 위치 및 날씨 정보 호출
  build.gradle
  gradlew
  src/main/java/org/ikuzo/otboo/OtbooApplication.java
  src/main/java/org/ikuzo/otboo/domain/user/exception/UserLocationMissingException.java
  src/main/java/org/ikuzo/otboo/domain/user/repository/UserRepository.java
  src/main/java/org/ikuzo/otboo/domain/weather/batch/WeatherBatchScheduler.java
  src/main/java/org/ikuzo/otboo/domain/weather/batch/WeatherCollectJobConfig.java
  src/main/java/org/ikuzo/otboo/domain/weather/client/KakaoApiProperties.java
  src/main/java/org/ikuzo/otboo/domain/weather/client/KakaoLocalClient.java
  src/main/java/org/ikuzo/otboo/domain/weather/client/WeatherApiClient.java
  src/main/java/org/ikuzo/otboo/domain/weather/client/WeatherApiProperties.java
  src/main/java/org/ikuzo/otboo/domain/weather/client/WeatherApiResponse.java
  src/main/java/org/ikuzo/otboo/domain/weather/controller/WeatherController.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/HumidityDto.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/KakaoRegionDocument.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/KakaoRegionMeta.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/KakaoRegionResponse.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/PrecipitationDto.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/PrecipitationType.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/RegionInfoDto.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/SkyStatus.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/TemperatureDto.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/WeatherAPILocation.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/WeatherDto.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/WeatherSummaryDto.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/WindSpeedDto.java
  src/main/java/org/ikuzo/otboo/domain/weather/dto/WindWord.java
  src/main/java/org/ikuzo/otboo/domain/weather/entity/Weather.java
  src/main/java/org/ikuzo/otboo/domain/weather/exception/WeatherException.java
  src/main/java/org/ikuzo/otboo/domain/weather/exception/WeatherNoForecastException.java
  src/main/java/org/ikuzo/otboo/domain/weather/mapper/WeatherMapper.java
  src/main/java/org/ikuzo/otboo/domain/weather/repository/WeatherRepository.java
  src/main/java/org/ikuzo/otboo/domain/weather/service/WeatherAlertService.java
  src/main/java/org/ikuzo/otboo/domain/weather/service/WeatherAlertServiceImpl.java
  src/main/java/org/ikuzo/otboo/domain/weather/service/WeatherReadService.java
  src/main/java/org/ikuzo/otboo/domain/weather/service/WeatherReadServiceImpl.java
  src/main/java/org/ikuzo/otboo/domain/weather/service/WeatherService.java
  src/main/java/org/ikuzo/otboo/domain/weather/service/WeatherServiceImpl.java
  src/main/java/org/ikuzo/otboo/domain/weather/util/KmaGridConverter.java
  src/main/java/org/ikuzo/otboo/global/exception/ErrorCode.java
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: Feat

#21 [DM] DM 목록 조회
  src/main/java/org/ikuzo/otboo/domain/directMessage/service/DirectMessageServiceImpl.java
Labels: Refactor

#23 [AttributeDefinition] 의상 속성 목록 조회
  src/main/java/org/ikuzo/otboo/domain/clothes/controller/ClothesAttributeDefController.java
  src/main/java/org/ikuzo/otboo/domain/clothes/controller/api/ClothesAttributeDefApi.java
  src/main/java/org/ikuzo/otboo/domain/clothes/dto/ClothesDto.java
  src/main/java/org/ikuzo/otboo/domain/clothes/dto/request/ClothesCreateRequest.java
  src/main/java/org/ikuzo/otboo/domain/clothes/dto/request/ClothesUpdateRequest.java
  src/main/java/org/ikuzo/otboo/domain/clothes/entity/Clothes.java
  src/main/java/org/ikuzo/otboo/domain/clothes/enums/AttributeDefSortBy.java
  src/main/java/org/ikuzo/otboo/domain/clothes/enums/AttributeDefSortDirection.java
  src/main/java/org/ikuzo/otboo/domain/clothes/enums/ClothesType.java
  src/main/java/org/ikuzo/otboo/domain/clothes/repository/ClothesAttributeDefRepository.java
  src/main/java/org/ikuzo/otboo/domain/clothes/repository/ClothesAttributeDefRepositoryCustom.java
  src/main/java/org/ikuzo/otboo/domain/clothes/repository/impl/ClothesAttributeDefRepositoryImpl.java
  src/main/java/org/ikuzo/otboo/domain/clothes/repository/impl/ClothesRepositoryImpl.java
  src/main/java/org/ikuzo/otboo/domain/clothes/service/ClothesAttributeDefService.java
  src/main/java/org/ikuzo/otboo/domain/clothes/service/impl/ClothesAttributeDefServiceImpl.java
  src/main/java/org/ikuzo/otboo/global/dto/PageResponse.java
Labels: Feat

#24 [AttributeDefinition] 의상 속성 관련 이슈 해결
  src/main/java/org/ikuzo/otboo/domain/clothes/service/impl/ClothesAttributeDefServiceImpl.java
  src/main/resources/schema.sql
Labels: Fix

#26 [Auth] 토큰 재발급
  src/main/java/org/ikuzo/otboo/domain/auth/controller/AuthController.java
  src/main/java/org/ikuzo/otboo/domain/auth/dto/JwtDto.java
  src/main/java/org/ikuzo/otboo/domain/auth/dto/JwtInformation.java
  src/main/java/org/ikuzo/otboo/domain/auth/service/AuthService.java
  src/main/java/org/ikuzo/otboo/domain/auth/service/AuthServiceImpl.java
  src/main/java/org/ikuzo/otboo/global/config/SecurityConfig.java
  src/main/java/org/ikuzo/otboo/global/exception/ErrorCode.java
  src/main/java/org/ikuzo/otboo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/ikuzo/otboo/global/security/JwtLoginSuccessHandler.java
  src/main/java/org/ikuzo/otboo/global/security/JwtTokenProvider.java
  src/main/resources/application.yaml
Labels: Feat

#28 [Notification] 알림 삭제 기능
  src/main/java/org/ikuzo/otboo/domain/notification/controller/NotificationController.java
  src/main/java/org/ikuzo/otboo/domain/notification/exception/NotificationException.java
  src/main/java/org/ikuzo/otboo/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/org/ikuzo/otboo/domain/notification/service/NotificationService.java
  src/main/java/org/ikuzo/otboo/domain/notification/service/NotificationServiceImpl.java
  src/main/java/org/ikuzo/otboo/global/exception/ErrorCode.java
  src/main/java/org/ikuzo/otboo/global/exception/GlobalExceptionHandler.java
Labels: Feat

#29 [DM] Websocket 인증/인가 처리
  build.gradle
  src/main/java/org/ikuzo/otboo/global/config/SecurityConfig.java
  src/main/java/org/ikuzo/otboo/global/config/WebsocketConfig.java
  src/main/java/org/ikuzo/otboo/global/security/JwtAuthenticationChannelInterceptor.java
  src/main/resources/static/websocket-test.html
Labels: Feat

#30 [Clothes] 구매 링크로 의상 정보 불러오기
  build.gradle
  src/main/java/org/ikuzo/otboo/domain/clothes/config/OpenAiClientConfig.java
  src/main/java/org/ikuzo/otboo/domain/clothes/config/OpenAiProps.java
  src/main/java/org/ikuzo/otboo/domain/clothes/controller/ClothesController.java
  src/main/java/org/ikuzo/otboo/domain/clothes/controller/api/ClothesApi.java
  src/main/java/org/ikuzo/otboo/domain/clothes/dto/ExtractClothes.java
  src/main/java/org/ikuzo/otboo/domain/clothes/extractions/OpenAiChatClient.java
  src/main/java/org/ikuzo/otboo/domain/clothes/extractions/OpenAiHtmlExtractor.java
  src/main/java/org/ikuzo/otboo/domain/clothes/parser/HtmlParserResolver.java
  src/main/java/org/ikuzo/otboo/domain/clothes/parser/JsoupHtmlParser.java
  src/main/java/org/ikuzo/otboo/domain/clothes/repository/ClothesAttributeDefRepository.java
  src/main/java/org/ikuzo/otboo/domain/clothes/service/ClothingExtractionService.java
  src/main/java/org/ikuzo/otboo/domain/clothes/service/impl/ClothingExtractionServiceImpl.java
  src/main/java/org/ikuzo/otboo/global/util/MimeTypeResolver.java
  src/main/java/org/ikuzo/otboo/global/util/S3ImageStorage.java
  src/main/resources/application.yaml
Labels: Feat

#34 [User] 프로필 조회
  src/main/java/org/ikuzo/otboo/domain/user/controller/UserController.java
  src/main/java/org/ikuzo/otboo/domain/user/dto/Location.java
  src/main/java/org/ikuzo/otboo/domain/user/dto/ProfileDto.java
  src/main/java/org/ikuzo/otboo/domain/user/entity/User.java
  src/main/java/org/ikuzo/otboo/domain/user/mapper/UserMapper.java
  src/main/java/org/ikuzo/otboo/domain/user/service/UserService.java
  src/main/java/org/ikuzo/otboo/domain/user/service/UserServiceImpl.java
Labels: Feat

#37 [Feed] 피드 삭제
  src/main/java/org/ikuzo/otboo/domain/feed/controller/FeedController.java
  src/main/java/org/ikuzo/otboo/domain/feed/dto/FeedUpdateRequest.java
  src/main/java/org/ikuzo/otboo/domain/feed/repository/FeedCustomRepositoryImpl.java
  src/main/java/org/ikuzo/otboo/domain/feed/service/FeedService.java
  src/main/java/org/ikuzo/otboo/domain/feed/service/FeedServiceImpl.java
Labels: Feat

#40 [Follow] 팔로우 도메인 리팩토링
  src/main/java/org/ikuzo/otboo/domain/follow/controller/FollowController.java
  src/main/java/org/ikuzo/otboo/domain/follow/service/FollowServiceImpl.java
Labels: Refactor

#41 [Recommendation] 의상 추천 (engine: Random)
  src/main/java/org/ikuzo/otboo/domain/clothes/mapper/ClothesMapper.java
  src/main/java/org/ikuzo/otboo/domain/clothes/repository/ClothesRepository.java
  src/main/java/org/ikuzo/otboo/domain/feed/dto/FeedDto.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/controller/RecommendationController.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/controller/api/RecommendationApi.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/dto/OotdDto.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/dto/RecommendationDto.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/entity/Recommend.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/entity/RecommendationClothes.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/repository/RecommendRepository.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/repository/RecommendationClothesRepository.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/service/RecommendationService.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/service/engine/RecommendationEngine.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/service/engine/impl/RandomRecommendationEngine.java
  src/main/java/org/ikuzo/otboo/domain/recommendation/service/impl/RecommendationServiceImpl.java
Labels: Feat

#45 [User] 권한 수정
  src/main/java/org/ikuzo/otboo/domain/user/controller/UserController.java
  src/main/java/org/ikuzo/otboo/domain/user/dto/UserRoleUpdateRequest.java
  src/main/java/org/ikuzo/otboo/domain/user/entity/User.java
  src/main/java/org/ikuzo/otboo/domain/user/service/UserService.java
  src/main/java/org/ikuzo/otboo/domain/user/service/UserServiceImpl.java
  src/main/java/org/ikuzo/otboo/global/config/SecurityConfig.java
  src/main/java/org/ikuzo/otboo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/ikuzo/otboo/global/security/AdminInitializer.java
  src/main/java/org/ikuzo/otboo/global/security/Http403ForbiddenAccessDeniedHandler.java
  src/main/resources/application.yaml
Labels: Feat

#47 [Comment] 댓글 생성 및 조회
  src/main/java/org/ikuzo/otboo/domain/comment/dto/CommentCreateRequest.java
  src/main/java/org/ikuzo/otboo/domain/comment/dto/CommentDto.java
  src/main/java/org/ikuzo/otboo/domain/comment/entity/Comment.java
  src/main/java/org/ikuzo/otboo/domain/comment/mapper/CommentMapper.java
  src/main/java/org/ikuzo/otboo/domain/comment/repository/CommentCustomRepository.java
  src/main/java/org/ikuzo/otboo/domain/comment/repository/CommentRepository.java
  src/main/java/org/ikuzo/otboo/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/org/ikuzo/otboo/domain/comment/service/CommentService.java
  src/main/java/org/ikuzo/otboo/domain/comment/service/CommentServiceImpl.java
  src/main/java/org/ikuzo/otboo/domain/feed/controller/CommentController.java
Labels: Feat

#50 [Weather] 날씨 API 변경
  src/main/java/org/ikuzo/otboo/domain/weather/client/WeatherApiClient.java
  src/main/java/org/ikuzo/otboo/domain/weather/service/WeatherReadServiceImpl.java
  src/main/resources/application.yaml
Labels: Fix

#56 [Auth] CSRF 토큰 조회 구현
  src/main/java/org/ikuzo/otboo/domain/auth/controller/AuthController.java
  src/main/java/org/ikuzo/otboo/global/config/SecurityConfig.java
  src/main/java/org/ikuzo/otboo/global/security/SpaCsrfTokenRequestHandler.java
Labels: Feat
